services:
  pg:
    image: postgres:16.3-bookworm
    ports:
      - 5435:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rss
